version: '2'
services:
    wesit-app:
        image: wesit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://wesit-postgresql:5432/wesit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=wesit-elasticsearch:9300
        ports:
            - 8080:8080
    wesit-postgresql:
        extends:
            file: postgresql.yml
            service: wesit-postgresql
    wesit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: wesit-elasticsearch
